spring:
  application:
    name: lmhps-curso-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost